CREATE TABLE IF NOT EXISTS af_table_nahai (
    `A_ID` VARCHAR(3) CHARACTER SET utf8,
    `Name` VARCHAR(50) CHARACTER SET utf8,
    `Label` VARCHAR(27) CHARACTER SET utf8,
    primary key(a_ID)
);
INSERT INTO af_table_nahai VALUES
    ('a1','<Rastakhiz_Party>','حزب رستاخیز ایران@fas'),
    ('a2','<Islamic_Republican_Party>','حزب جمهوري اسلامي ايران@fas'),
    ('a3','<Islamic_Society_of_Engineers>','جامعهٔ اسلامي مهندسين@fas'),
    ('a4','<Revival_Party>',NULL),
    ('a5','<National_Front_(Iran)>',NULL),
    ('a7','<Freedom_Movement_of_Iran>',NULL),
    ('a9','<Combatant_Clergy_Association>',NULL),
    ('a11','<Islamic_Coalition_Party>',NULL),
    ('a12','<Executives_of_Construction_Party>',NULL),
    ('a13','<Iranian_reform_movement>',NULL),
    ('a16','<Nation_Party_of_Iran>',NULL),
    ('a17','<Pan-Iranist_Party>',NULL),
    ('a19','<Alliance_of_Builders_of_Islamic_Iran>',NULL),
    ('a20','<Socialist_Party_(Iran)>',NULL),
    ('a21','<Association_of_Combatant_Clerics>',NULL),
    ('a23','<Front_of_Islamic_Revolution_Stability>',NULL),
    ('a28','<Independent_(politician)>',NULL),
    ('a29','<Hojjatieh>',NULL),
    ('a32','<National_Trust_Party_(Iran)>',NULL),
    ('a39','<Society_of_Devotees_of_the_Islamic_Revolution>',NULL),
    ('a48','<Constitutionalist_Party_of_Iran>',NULL),
    ('a54','<People''s_Mujahedin_of_Iran>',NULL),
    ('a55','<Armed_Forces_of_the_Islamic_Republic_of_Iran>',NULL),
    ('a60','<New_Iran_Party>',NULL),
    ('a64','<Mojahedin_of_the_Islamic_Revolution_Organization>',NULL),
    ('a66','<Liberal_Party>',NULL),
    ('a77','<Mohammad_Khatami>',NULL),
    ('a79','<Islamic_Iran_Participation_Front>',NULL),
    ('a80','<The_Green_Path_of_Hope>',NULL),
    ('a84','<Monarchist_Party>',NULL),
    ('a86','<E''tedalion_Party>',NULL);
