CREATE TABLE IF NOT EXISTS islamic_countries (
    `C_ID` VARCHAR(3) CHARACTER SET utf8,
    `Name` VARCHAR(22) CHARACTER SET utf8,
    `Label` VARCHAR(32) CHARACTER SET utf8,
    primary key(C_ID)
);
INSERT INTO islamic_countries VALUES
    ('c1','<Uzbekistan>','ازبكستان@fas'),
    ('c2','<Yemen>','جمهوري يمن@fas'),
    ('c3','<Egypt>','مصري@fas'),
    ('c4','<Kuwait>','کویت@fas'),
    ('c5','<Iran>','امپراطوري ايران@fas'),
    ('c6','<Iraq>','عراق@fas'),
    ('c7','<Libya>','ليبي@fas'),
    ('c8','<Saudi_Arabia>','السعوديه.@fas'),
    ('c9','<Palestine>','مناطق خودمختار فلسطینی@fas'),
    ('c10','<Malaysia>','مالیزیا@fas'),
    ('c11','<Tajikistan>','تاجيكستان@fas'),
    ('c12','<United_Arab_Emirates>','امارات متحد عربي@fas'),
    ('c13','<Jordan>','اردن هاشمي@fas'),
    ('c14','<Indonesia>','اندونزی@fas'),
    ('c15','<Sudan>','سودان@fas'),
    ('c16','<Mauritania>','جمهوری اسلامی موریتانیا@fas'),
    ('c17','<Qatar>','قطر (کشور)@fas'),
    ('c18','<Bahrain>','پادشاهي بحرين@fas'),
    ('c19','<Afghanistan>','جمهوری اسلامی افغانستان@fas'),
    ('c20','<Islamic_state>','حكومت اسلامي@fas'),
    ('c21','<Turkmenistan>','جمهوری ترکمنستان@fas'),
    ('c22','<Tunisia>','جمهوري تونس@fas'),
    ('c23','<Pakistan>','پاکستانی@fas'),
    ('c24','<Algeria>','جمهوری دموکراتیک خلق الجزایر@fas'),
    ('c25','<Maldives>','مالدیو@fas'),
    ('c26','<Oman>','عمان@fas'),
    ('c27','<Turkey>','جمهوري تركيه@fas'),
    ('c28','<Syria>','سورستان@fas'),
    ('c29','<Azawad>','ازاواد@fas'),
    ('c30','<Lebanon>','لبناني@fas');
