CREATE TABLE Politicians_table (
    `P_ID` VARCHAR(4) CHARACTER SET utf8,
    `Name` VARCHAR(39) CHARACTER SET utf8,
    `Gender` VARCHAR(8) CHARACTER SET utf8,
    `Born_In` VARCHAR(15) CHARACTER SET utf8,
    `Died_IN` VARCHAR(22) CHARACTER SET utf8,
    `Website` VARCHAR(49) CHARACTER SET utf8,
    `Label` VARCHAR(35) CHARACTER SET utf8,
    primary key(p_ID)
);
INSERT INTO Politicians_table VALUES
    ('p1','<Jafar_Sharif-Emami>','<male>','<Tehran>','<New_York_City>',NULL,'شریف امامی@fas'),
    ('p2','<Abbas_Adham>','<male>',NULL,NULL,NULL,'Abbas Adham@eng'),
    ('p3','<Morteza_Mohammadkhan>','<male>','<Tehran>',NULL,NULL,'مرتضي محمدخان@fas'),
    ('p4','<Ali_Larijani>','<male>','<Najaf>',NULL,NULL,'علي املي لاريجاني@fas'),
    ('p5','<Mohammadreza_Nematzadeh>','<male>','<Tabriz>',NULL,NULL,'محمدرضا نعمت‌زاده@fas'),
    ('p6','<Mirza_Ali_Asghar_Khan_Amin_al-Sultan>',NULL,'<Tehran>','<Tehran>',NULL,'ميرزا علي اصغر امين السلطان@fas'),
    ('p7','<de/Abolqasem_Naser_al_Molk>',NULL,NULL,NULL,NULL,'Abolqasem Naser al Molk@eng'),
    ('p8','<Ahmad_Qavam>','<male>','<Tehran>','<Tehran>',NULL,'احمد قوام السلطنه@fas'),
    ('p9','<Firouz_Nosrat-ed-Dowleh_III>','<male>','<Tehran>',NULL,NULL,'Firouz Nosrat-ed-Dowleh III@eng'),
    ('p10','<Hosein_Dadgar>','<male>',NULL,NULL,NULL,'Dadgar'),
    ('p11','<Hajj_Mirza_Aghasi>','<male>','<Maku,_Iran>',NULL,NULL,'حاجي ميرزا آقاسي@fas'),
    ('p12','<Gholam_Hossein_Sadighi>','<male>','<Tehran>','<Tehran>',NULL,'غلامحسين صديقي@fas'),
    ('p13','<Ahmad_Sadegh-Bonab>','<male>',NULL,NULL,NULL,'Ahmad'),
    ('p14','<Mohammad_Bahrami>',NULL,NULL,NULL,NULL,'Mohammad Bahrami@eng'),
    ('p15','<Mohammad-Ali_Rajai>','<male>','<Qazvin>','<Tehran>',NULL,'رجایی@fas'),
    ('p16','<Ali_Jannati>','<male>',NULL,NULL,NULL,'علی جنتی@fas'),
    ('p17','<Hossein_Fatemi>','<male>','<Nain,_Iran>','<Tehran>',NULL,'سیدحسین فاطمی@fas'),
    ('p18','<Mohammad-Reza_Mahdavi_Kani>','<male>','<Tehran>',NULL,'<http://www.MahdaviKani.ir/>','محمد رضا مهدوي كني@fas'),
    ('p19','<Karim_Sanjabi>','<male>','<Kermanshah>','<Carbondale,_Illinois>',NULL,'كريم سنجابي@fas'),
    ('p20','<Alireza_Marandi>','<male>','<Isfahan>',NULL,NULL,'علي رضا مرندي@fas'),
    ('p21','<Mohammad-Reza_Hekmat>','<male>',NULL,NULL,NULL,'Sardar Fakher Hekmat@eng'),
    ('p22','<Marzieh_Vahid-Dastjerdi>','<female>','<Tehran>',NULL,NULL,'مرضیهٔ وحید دستجردی@fas'),
    ('p23','<Ahmad_Tavakkoli>','<male>','<Behshahr>',NULL,'<http://www.alef.ir/>','احمد توکلی@fas'),
    ('p24','<Akbar_Hashemi_Rafsanjani>','<male>','<Bahreman>',NULL,'<http://www.rafsanjani.ir/>','Ali Akbar Hāshemī Rafsanjānī@eng'),
    ('p25','<Bijan_Namdar_Zangeneh>','<male>','<Kermanshah>',NULL,NULL,'بيژن زنگنه@fas'),
    ('p26','<Tahmasb_Mazaheri>','<male>','<Tehran>',NULL,NULL,'طهماسب مظاهری@fas'),
    ('p27','<Parviz_Kazemi>','<male>','<Tehran>',NULL,NULL,'پرويز كاظمي@fas'),
    ('p28','<Mehdi_Bazargan>','<male>','<Tehran>','<Zürich>','<http://www.bazargan.info/la_english/english.htm>','مهدی بازرگان@fas'),
    ('p29','<Mohammad-Taqi_Bahar>','<male>','<Mashhad>','<Tehran>','<http://www.bahar-site.fr/>','ملک الشعراء بهار@fas'),
    ('p30','<Ahmad_Hussein_Adl>','<male>',NULL,NULL,NULL,'Ahmad'),
    ('p31','<Abbas_Ali_Khalatbari>','<male>','<Tehran>','<Tehran>',NULL,'عباسعلي خلعتبري@fas'),
    ('p32','<Hossein_Navab>','<male>',NULL,NULL,NULL,'Hossein'),
    ('p33','<Mozaffar_Alam>','<male>',NULL,NULL,NULL,'Mozzafar Alam@eng'),
    ('p34','<Dariush_Forouhar>','<male>','<Isfahan>','<Tehran>',NULL,'داريوش فروهر@fas'),
    ('p35','<Shapour_Bakhtiar>','<male>','<Izeh>','<Paris>',NULL,'دکتر شاپور بختیار@fas'),
    ('p36','<Mohammad_Vali_Khan_Tonekaboni>','<male>','<Tonekabon>','<Tehran>',NULL,'سپهدار اعظم تنکابنی@fas'),
    ('p37','<Mahmoud_Ahmadinejad>','<male>','<Aradan,_Iran>',NULL,'<http://www.ahmadinejad.ir/>','احمدی‌نژاد@fas'),
    ('p38','<Hekmat_E_Shirazi>','<male>',NULL,NULL,NULL,'Shirazi'),
    ('p39','<Abolqasem_Najm>','<male>','<Tehran>','<Tehran>',NULL,'نجم الملك@fas'),
    ('p40','<Ali_Amini>','<male>','<Tehran>','<Paris>',NULL,'علی امینی@fas'),
    ('p41','<Mohsen_Sadr>','<male>','<Mahallat>','<Tehran>',NULL,'صدرالاشراف@fas'),
    ('p42','<Mohammad_Saeedikia>','<male>','<Isfahan>',NULL,NULL,'محمد سعیدی کیا@fas'),
    ('p43','<Gholam_Reza_Azhari>','<male>','<Shiraz>',NULL,NULL,'ازهاري@fas'),
    ('p44','<Mohammad_Salimi>','<male>',NULL,NULL,NULL,'محمد سلیمی@fas'),
    ('p45','<Manouchehr_Eghbal>','<male>','<Mashhad>','<Tehran>',NULL,'منوچهر اقبال@fas'),
    ('p46','<Mehdi_Ghazanfari>',NULL,'<Aligudarz>',NULL,NULL,'مهدی غضنفری@fas'),
    ('p47','<Gholam_Hossein_Jahanshahi>','<male>',NULL,NULL,NULL,'Jahanshahi'),
    ('p48','<Zahra_Shojaei>',NULL,NULL,NULL,NULL,'Shojaei'),
    ('p49','<Alireza_Tahmasbi>','<male>','<Shiraz>',NULL,NULL,'علیرضا طهماسبی@fas'),
    ('p50','<Ali_Akbar_Mohtashamipur>','<male>','<Tehran>',NULL,NULL,'علي اكبر محتشمي@fas'),
    ('p51','<Mohammad-Javad_Bahonar>','<male>','<Kerman>','<Tehran>',NULL,'آيت الله دكتر باهنر@fas'),
    ('p52','<Ahmad_Amir-Ahmadi>','<male>','<Tehran>','<Tehran>',NULL,'احمداقا سرتيپ@fas'),
    ('p53','<Abdollah_Nouri>','<male>','<Isfahan>',NULL,NULL,'عبدالله نوري@fas'),
    ('p54','<Jahangir_Amuzegar>','<male>',NULL,NULL,NULL,'جهانگير آموزگار@fas'),
    ('p55','<Ahmad_Khorram>','<male>','<Isfahan>',NULL,NULL,'احمد خرم@fas'),
    ('p56','<Esmail_Shooshtari>','<male>','<Nishapur>',NULL,NULL,'محمداسماعیل شوشتری@fas'),
    ('p57','<Shamseddin_Hosseini>','<male>','<Tonekabon>',NULL,NULL,'سید شمس‌الدین حسینی@fas'),
    ('p58','<Habibollah_Bitaraf>','<male>',NULL,NULL,NULL,'حبیب الله بیطرف@fas'),
    ('p59','<Sadegh_Mahsouli>','<male>','<Urmia>',NULL,NULL,'محمدصادق محصولي@fas'),
    ('p60','<Cabinet_of_Iran>','<male>',NULL,NULL,NULL,'کابینه ایران@fas'),
    ('p61','<Kazem_Vaziri_Hamaneh>','<male>','<Yazd>',NULL,NULL,'Kazem Vaziri Hamane@eng'),
    ('p62','<Kamal_Habibollahi>','<male>',NULL,NULL,NULL,'کمال الدین میرحبیب اللهی@fas'),
    ('p63','<Mohammad-Reza_Bahonar>','<male>','<Kerman>',NULL,NULL,'محمد رضا باهنر@fas'),
    ('p64','<Mirza_Hosein_Khan_Moshir_od-Dowleh>','<male>',NULL,NULL,NULL,'ميرزا حسين خان مشيرالدوله@fas'),
    ('p65','<Jamal_Karimi-Rad>','<male>','<Qazvin>','<Salafchegan>',NULL,'جمال كريمي راد@fas'),
    ('p66','<Hassan_Rouhani>','<male>','<Sorkheh>',NULL,NULL,'حسن فریدون@fas'),
    ('p67','<Mostafa_Pourmohammadi>','<male>','<Qom>',NULL,NULL,'مصطفي پورمحمدي@fas'),
    ('p68','<Hossein_Kamali>','<male>',NULL,NULL,NULL,'حسین کمالی@fas'),
    ('p69','<Abdullah_Entezam>','<male>',NULL,'<Tehran>',NULL,'عبدالله انتظام وزیری@fas'),
    ('p70','<Kamal_Kharazi>','<male>','<Tehran>',NULL,NULL,'كمال خرازي@fas'),
    ('p71','<Mohammad_Reza_Ameli_Tehrani>','<male>','<Tehran>','<Tehran>',NULL,'محمد رضا عاملی تهرانی@fas'),
    ('p72','<Ahmad_Mirfendereski>','<male>',NULL,NULL,NULL,'Ahmad Mirfendereski'),
    ('p73','<Ali_Akbar_Moinfar>','<male>',NULL,NULL,NULL,'Ali'),
    ('p74','<Ali_Shamkhani>','<male>','<Ahvaz>',NULL,NULL,'شمخانی@fas'),
    ('p75','<Ahmad_Vahidi>','<male>','<Shiraz>',NULL,NULL,'سردار احمد وحیدی@fas'),
    ('p76','<Masoud_Pezeshkian>','<male>','<Tabriz>',NULL,NULL,'مسعود پزشكيان@fas'),
    ('p77','<Mostafa_Chamran>','<male>','<Tehran>',NULL,NULL,'مصطفی چمران ساوجی@fas'),
    ('p78','<Manouchehr_Ganji>','<male>','<Tehran>',NULL,NULL,'Ganji'),
    ('p79','<Ahmad_Masjed-Jamei>','<male>','<Tehran>',NULL,NULL,'احمد مسجد جامعي@fas'),
    ('p80','<Amir_Khosrow_Afshar>','<male>',NULL,NULL,NULL,'Amir Khosrow Afshar@eng'),
    ('p81','<Hasan_Arsanjani>','<male>','<Tehran>',NULL,NULL,'حسن ارسنجاني@fas'),
    ('p82','<Majid_Namjoo>','<male>','<Kerman>',NULL,NULL,'مجيد نامجو@fas'),
    ('p83','<Abbas_Aram>','<male>',NULL,NULL,NULL,'Abbas Aram'),
    ('p84','<Isa_Kalantari>','<male>',NULL,NULL,NULL,'Kalantari'),
    ('p85','<Mohammad_Javad_Zarif>','<male>','<Tehran>',NULL,NULL,'جواد ظريف@fas'),
    ('p86','<Mohammad_Ardakani>','<male>',NULL,NULL,NULL,'Ardakani'),
    ('p87','<Ahmad_Sayyed_Javadi>','<male>','<Qazvin>','<Tehran>',NULL,'احمد صدرحاج سید جوادی@fas'),
    ('p88','<Hasan_Arfa>','<male>',NULL,NULL,NULL,'حسن ارفع@fas'),
    ('p89','<Morteza_Gholi_Khan_Hedayat>','<male>','<Tehran>','<Tehran>',NULL,'مرتضی‌قلی‌خان هدایت@fas'),
    ('p90','<Reza_Sheykholeslam>','<male>','<Chalus,_Iran>',NULL,NULL,'عبدالرضا شيخ الاسلامي@fas'),
    ('p91','<Ali_Akbar_Mehrabian>','<male>',NULL,NULL,NULL,'علي اكبر محرابيان@fas'),
    ('p92','<fr/Mehdi_Gholi_Hedayat>',NULL,NULL,NULL,NULL,'Mehdi Hedayat@fr'),
    ('p93','<Eshaq_Jahangiri>','<male>','<Sirjan>',NULL,'<http://president.ir/fa/vicepresident>','اسحاق جهانگيري@fas'),
    ('p94','<Ali-Akbar_Zargham>','<male>',NULL,NULL,NULL,'AliAkbar Zargham@eng'),
    ('p95','<Kamran_Bagheri_Lankarani>','<male>','<Tehran>',NULL,NULL,'کامران باقری لنکرانی@fas'),
    ('p96','<Gholam_Reza_Aghazadeh>','<male>','<Khoy>',NULL,NULL,'غلامرضا اقازاده@fas'),
    ('p97','<Mohammad_Soleimani>','<male>','<Khesht>',NULL,NULL,'محمد سلیمانی@fas'),
    ('p98','<Mohammad_Jahromi>','<male>',NULL,NULL,NULL,'Mohammad'),
    ('p99','<Hassan_Habibi>','<male>','<Tehran>',NULL,NULL,'حسن حبيبي@fas'),
    ('p100','<Mohammad_Reza_Rahimi>','<male>','<Serishabad>',NULL,NULL,'محمد رضا رحیمی@fas'),
    ('p101','<Parviz_Varjavand>','<male>','<Tehran>','<Tehran>',NULL,'پرویز ورجاوند@fas'),
    ('p102','<Abdol_Majid_Mirza>',NULL,NULL,NULL,NULL,'عین‌الدوله@fas'),
    ('p103','<Abbas_Ahmad_Akhoundi>','<male>',NULL,NULL,NULL,'عباس احمد آخوندی@fas'),
    ('p104','<Ardeshir_Zahedi>','<male>','<Tehran>',NULL,NULL,'اردشير زاهدي@fas'),
    ('p105','<Manouchehr_Mottaki>','<male>','<Bandar-e_Gaz>',NULL,NULL,'متکی@fas'),
    ('p106','<Mirza_Nasrullah_Khan>','<male>',NULL,'<Tehran>',NULL,'نصرالله مشیرالدوله@fas'),
    ('p107','<Masoud_Mir_Kazemi>','<male>','<Tehran>',NULL,NULL,'مسعود میر کاظمی@fas'),
    ('p108','<Reza_Malekzadeh>','<male>',NULL,NULL,NULL,'رضا ملك زاده@fas'),
    ('p109','<Ata''ollah_Mohajerani>','<male>','<Arak,_Iran>',NULL,'<http://mohajerani.maktuob.net>','سید عطاالله مهاجرانی@fas'),
    ('p110','<Ali_Kordan>','<male>',NULL,'<Tehran>',NULL,'علي كردان@fas'),
    ('p111','<de/Ebrahim_Alam>',NULL,NULL,NULL,NULL,'Ebrahim Alam@de'),
    ('p112','<Mahmoud_Jam>',NULL,NULL,NULL,NULL,'محمود جم@fas'),
    ('p113','<Esfandiar_Rahim_Mashaei>','<male>',NULL,NULL,NULL,'اسفندیار رحیم‌مشایی@fas'),
    ('p114','<Farrokhroo_Parsa>','<female>','<Qom>','<Tehran>',NULL,'فَرُّخ‌رو پارسا@fas'),
    ('p115','<Morteza-Qoli_Bayat>','<male>','<Arak,_Iran>','<Tehran>',NULL,'سهام السلطان بيات@fas'),
    ('p116','<Mohammad-Ali_Najafi>','<male>','<Tehran>',NULL,NULL,'محمدعلی نجفی (معاون رییس جمهور)@fas'),
    ('p117','<Iraj_Eskandari>','<male>','<Tehran>','<East_Berlin>',NULL,'ايرج اسكندري@fas'),
    ('p118','<Ahmad_Madani>','<male>','<Kerman>','<Denver>',NULL,'احمد مدني@fas'),
    ('p119','<Ali_Soheili>','<male>','<Tabriz>','<London>',NULL,'علی سهیلی@fas'),
    ('p120','<Mehdi_Qoli_Hedayat>','<male>','<Tehran>','<Tehran>',NULL,'ميرزا مهدي قلي خان مخبرالسلطنه@fas'),
    ('p121','<Vosough_od-Dowleh>','<male>','<Tehran>','<Tehran>',NULL,'حسن وثوق@fas'),
    ('p122','<Fathollah_Khan_Akbar>','<male>','<Rasht>','<Tehran>',NULL,'فتح الله خان سپهدار رشتی@fas'),
    ('p123','<Mohammad_Hossein_Jalali>','<male>',NULL,NULL,NULL,'Jalali'),
    ('p124','<Mohammad_Hosseini_(politician)>','<male>',NULL,NULL,NULL,'Mohammad Hosseini (politician)@eng'),
    ('p125','<Ali_Mansur>','<male>','<Tehran>','<Tehran>',NULL,'منصور الملک@fas'),
    ('p126','<Mostowfi_ol-Mamalek>','<male>','<Tehran>','<Tehran>',NULL,'حسن مستوفی‌الممالک@fas'),
    ('p127','<Mirza_Ali_Asghar_Khan_Amin_al-Soltan>','<male>','<Tehran>','<Tehran>',NULL,'al-Soltan'),
    ('p128','<Mohammad_Forouzandeh>','<male>',NULL,NULL,NULL,'Mohammad'),
    ('p129','<Mohammad_Reyshahri>','<male>','<Rey,_Iran>',NULL,NULL,'ری شهری@fas'),
    ('p130','<Rahman_Dadman>','<male>','<Ardabil>',NULL,NULL,'رحمان دادمان@fas'),
    ('p131','<Rostam_Ghasemi>','<male>',NULL,NULL,NULL,'رستم قاسمي@fas'),
    ('p132','<Mirza_Abolhassan_Khan_Ilchi>','<male>',NULL,NULL,NULL,'ابوالحسن شیرازی@fas'),
    ('p133','<Ali_Akbar_Velayati>','<male>','<Tehran>',NULL,'<http://www.velayati.ir>','علی‌اکبر ولایتی@fas'),
    ('p134','<Saad_ad-Daula>','<male>',NULL,'<Isfahan>',NULL,'نجفقلی بختیاری@fas'),
    ('p135','<Mohsen_Nourbakhsh>','<male>','<Isfahan>','<Tehran>',NULL,'سيد محسن نوربخش@fas'),
    ('p136','<Mohammad_Gharazi>','<male>','<Isfahan>',NULL,NULL,'مهندس غرضي@fas'),
    ('p137','<Hassan_Taqizadeh>','<male>','<Tabriz>','<Tehran>',NULL,'تقی‌زاده@fas'),
    ('p138','<Akbar_Torkan>','<male>','<Tehran>',NULL,NULL,'اكبر تركان@fas'),
    ('p139','<Fazlollah_Zahedi>','<male>','<Hamedan>','<Geneva>',NULL,'فضل الله خان بصير ديوان@fas'),
    ('p140','<Sadegh_Ghotbzadeh>','<male>','<Isfahan>','<Tehran>',NULL,'صادق قطب زاده@fas'),
    ('p141','<Amir-Abbas_Hoveyda>','<male>','<Tehran>','<Tehran>',NULL,'عباس هويدا@fas'),
    ('p142','<Jamshid_Amouzegar>','<male>','<Tehran>',NULL,NULL,'جمشید اموزگار@fas'),
    ('p143','<Ali_Younesi>','<male>','<Nahavand>',NULL,NULL,'علي يونسي@fas'),
    ('p144','<Mostafa_Mohammad-Najjar>','<male>','<Tehran>',NULL,NULL,'محمد مصطفي نجار@fas'),
    ('p145','<Gholam-Hossein_Elham>',NULL,'<Andimeshk>',NULL,NULL,'غلامحسين الهام@fas'),
    ('p146','<Hashemi_Rafsanjani>',NULL,'<Bahreman>',NULL,NULL,'حجت الاسلام هاشمی رفسنجانی@fas'),
    ('p147','<Ali_Fallahian>','<male>','<Najafabad>',NULL,NULL,'فلاحیان@fas'),
    ('p148','<Behzad_Nabavi>','<male>','<Tehran>',NULL,NULL,'بهزاد نبوي@fas'),
    ('p149','<Hassan_Pakravan>','<male>','<Tehran>','<Tehran>',NULL,'حسن پاکروان@fas'),
    ('p150','<Asadollah_Alam>','<male>','<Birjand>','<New_York_City>',NULL,'امير اسدالله علم@fas'),
    ('p151','<Kazem_Sami>','<male>','<Mashhad>','<Tehran>',NULL,'دکتر سامی@fas'),
    ('p152','<Nematollah_Nassiri>','<male>','<Semnan,_Iran>','<Tehran>',NULL,'سرلشكر نصيري@fas'),
    ('p153','<Asadollah_Abbasi>','<male>',NULL,NULL,NULL,'Asadollah'),
    ('p154','<Ali_Mohammad_Besharati>','<male>',NULL,NULL,NULL,'Ali Mohammad Besharati@eng'),
    ('p155','<Abdolhossein_Hazhir>','<male>','<Kashan>','<Tehran>',NULL,'هژير@fas'),
    ('p156','<Gholamreza_Nikpey>','<male>','<Isfahan>','<Tehran>',NULL,'غلامرضا نيك پي@fas'),
    ('p157','<Mohammad_Mehdi_Zahedi>','<male>','<Kerman>',NULL,NULL,'محمد‌مهدی زاهدی@fas'),
    ('p158','<Reza_Taghipour>','<male>','<Maragheh>',NULL,NULL,'رضا تقی‌پور انواری@fas'),
    ('p159','<Habibollah_Asgaroladi>','<male>','<Tehran>',NULL,NULL,'حبيب الله عسكراولادي@fas'),
    ('p160','<Mousa_Namjoo>','<male>',NULL,NULL,NULL,'Namjoo'),
    ('p161','<Ali_Tayebnia>','<male>',NULL,NULL,NULL,'Ali Tayebnia'),
    ('p162','<Hushang_Ansary>','<male>','<Ahvaz>',NULL,NULL,'هوشنگ انصاري@fas'),
    ('p163','<fr/Reza_Sardar_Fakher_Hekmat>',NULL,NULL,NULL,NULL,'Hekmat@fr'),
    ('p164','<Hossein_Dehghan>','<male>','<Dehaqan>',NULL,NULL,'حسين دهقان@fas'),
    ('p165','<Parviz_Fattah>','<male>','<Urmia>',NULL,NULL,'سید پرویز فتاح@fas'),
    ('p166','<Ghorbanali_Dorri-Najafabadi>','<male>','<Rey,_Iran>',NULL,NULL,'قربانعلی دری نجف ابادی@fas'),
    ('p167','<Ali_Khamenei>','<male>','<Mashhad>',NULL,'<http://khamenei.ir>','ایه‌الله خامنه‌ای@fas'),
    ('p168','<Ebrahim_Yazdi>','<male>','<Qazvin>',NULL,NULL,'ابراهم يزدي@fas'),
    ('p169','<Amir_Kabir>','<male>','<Arak,_Iran>','<Kashan>',NULL,'میرزا تقی خان امیر کبیر@fas'),
    ('p170','<Mahmoud_Hessaby>','<male>',NULL,'<Geneva>',NULL,'دکتر محمود حسابی@fas'),
    ('p171','<Hossein_Ala''>','<male>','<Tehran>','<Tehran>',NULL,'حسين علاء@fas'),
    ('p172','<Saeed_Emami>','<male>',NULL,NULL,NULL,'سعيدامامي@fas'),
    ('p173','<Ali_Nikzad>','<male>','<Ardabil>',NULL,NULL,'نیکزاد@fas'),
    ('p174','<Haj_Ali_Razmara>','<male>','<Tehran>',NULL,NULL,'حاجیعلی رزم آرا@fas'),
    ('p175','<Haji_Washington>','<male>',NULL,NULL,NULL,'حاجي واشنگتن@fas'),
    ('p176','<Mohammad_Shariatmadari>','<male>',NULL,NULL,NULL,'Mohammad Shariatmadari@eng'),
    ('p177','<Hashem_Sabbaghian>','<male>','<Tehran>',NULL,NULL,'هاشم صباغيان@fas'),
    ('p178','<Ismail_Mumtaz>','<male>',NULL,NULL,NULL,'اسماعيل ممتاز@fas'),
    ('p179','<Mohammad-Reza_Eskandari>',NULL,'<Ahvaz>',NULL,NULL,'محمدرضا اسكندري@fas'),
    ('p180','<Hamid-Reza_Haji_Babaee>','<male>','<Hamedan>',NULL,NULL,'حاجی‌بابایی@fas'),
    ('p181','<Safdar_Hosseini>','<male>',NULL,NULL,NULL,'سید صفدر حسینی@fas'),
    ('p182','<Ali_Shariatmadari>','<male>','<Shiraz>',NULL,NULL,'علي شريعتمداري@fas'),
    ('p183','<Abdolvahed_Mousavi_Lari>','<male>','<Tehran>',NULL,NULL,'عبدالواحد موسوي لاري@fas'),
    ('p184','<Mirza_Hassan_Khan_Esfandiary>','<male>',NULL,NULL,NULL,'Mirza Hassan Khan Esfandiary@eng'),
    ('p185','<nl/Jafaar_Sharif-Emami>',NULL,NULL,NULL,NULL,'Jafaar Sharif-Emami@eng'),
    ('p186','<Hossein_Ghods-Nakhai>','<male>',NULL,'<Tehran>',NULL,'Hossein Ghods-Nakhai@eng'),
    ('p187','<Zia''eddin_Tabatabaee>','<male>','<Shiraz>','<Tehran>',NULL,'سیدضیاالدین طباطبائی@fas'),
    ('p188','<Alireza_Ali_Ahmadi>','<male>','<Isfahan>',NULL,NULL,'علیرضا علی‌احمدی@fas'),
    ('p189','<Davoud_Danesh-Jafari>','<male>','<Tehran>',NULL,NULL,'داود دانش جعفری@fas'),
    ('p190','<Ebrahim_Hakimi>','<male>','<Tabriz>','<Tehran>',NULL,'ابراهیم حکیم الممالک@fas'),
    ('p191','<Ali_Akbar_Nategh-Nouri>','<male>','<Nur,_Iran>',NULL,NULL,'علی‌اکبر ناطق نوری@fas'),
    ('p192','<Mohammad_Mosaddegh>','<male>','<Tehran>','<Ahmadabad-e_Mosaddeq>',NULL,'محمد مصدق السلطنه@fas'),
    ('p193','<Ali_Akbar_Siassi>','<male>',NULL,NULL,NULL,'Ali-Akbar Siassi@eng'),
    ('p194','<Mohammad_Khatami>','<male>','<Ardakan>',NULL,'<http://www.Khatami.ir/>','سید محمدخاتمی@fas'),
    ('p195','<Nasser_Minachi>','<male>',NULL,NULL,NULL,'Nasser Minachi'),
    ('p196','<Ali-Akbar_Davar>','<male>','<Tehran>','<Tehran>',NULL,'علي اكبر داور@fas'),
    ('p197','<Gholam-Hossein_Mohseni-Eje''i>','<male>','<Isfahan>',NULL,NULL,'غلامحسين اژه اي@fas'),
    ('p198','<Iradj_Fazel>','<male>','<Ardestan>',NULL,NULL,'ايرج فاضل@fas'),
    ('p199','<Mohammad_Abbasi>','<male>',NULL,NULL,NULL,'محمد عباسي@fas'),
    ('p200','<Hamid_Chitchian>','<male>',NULL,NULL,NULL,'Hamid Chitchian@eng'),
    ('p201','<Mohammad_Reza_Aref>','<male>','<Yazd>',NULL,'<http://ee.sharif.edu/>','دكتر عارف@fas'),
    ('p202','<Hossein_Saffar_Harandi>','<male>','<Gorgan>',NULL,NULL,'صفار هرندي@fas'),
    ('p203','<Rezā_Shāh>','<male>','<Alasht>','<Johannesburg>',NULL,'رضا خان پهلوي@fas'),
    ('p204','<Mir-Hossein_Mousavi>','<male>','<Khamaneh>',NULL,'<http://www.kaleme.org/>','میرحسین موسوی خامنه ای@fas'),
    ('p205','<Parviz_Davoodi>','<male>','<Tehran>',NULL,NULL,'پرويز داودي@fas'),
    ('p206','<Ahmad_Motamedi>','<male>',NULL,NULL,NULL,'Ahmad'),
    ('p207','<Abdolhossein_Teymourtash>','<male>','<Bojnord>','<Tehran>',NULL,'عبدالحسین تیمورتاش@fas'),
    ('p208','<Mohsen_Rais>','<male>',NULL,NULL,NULL,'Mohsen Rais@eng'),
    ('p209','<Amir_Abdollah_Tahmasebi>','<male>','<Tehran>','<Borujerd>',NULL,'عبدالله‌خان امیر طهماسبی@fas'),
    ('p210','<Ahmad_Matin-Daftari>','<male>','<Tehran>','<Tehran>',NULL,'متین الدوله@fas'),
    ('p211','<Gholam_Hossein_Nozari>','<male>','<Kazerun>',NULL,NULL,'غلامحسين نوذري@fas'),
    ('p212','<Ghaem_Magham_Farahani>','<male>','<Arak,_Iran>','<Tehran>',NULL,'قائم مقام فراهانی@fas'),
    ('p213','<Mahmoud_Djam>','<male>','<Tabriz>','<Tehran>',NULL,'Mahmoud Djam@eng'),
    ('p214','<de/Najaf_Qoli_Khan_Samsam_al-Saltaneh>',NULL,NULL,NULL,NULL,'Saltaneh@deu'),
    ('p215','<Kamran_Daneshjoo>','<male>','<Damghan>',NULL,NULL,'كامران دانشجو@fas'),
    ('p216','<Mohsen_Rafighdoost>','<male>','<Tehran>',NULL,NULL,'محسن رفيق دوست@fas'),
    ('p217','<Mahmoud_Farshidi>','<male>',NULL,NULL,NULL,'Mahmoud'),
    ('p218','<de/Mohammad_Ali_Khan_Ala_al-Saltaneh>',NULL,NULL,NULL,NULL,'میرزا محمدعلی خان علاءالسلطنه@fas'),
    ('p219','<Sadeq_Khalilian>','<male>',NULL,NULL,NULL,'Sadeq Khalilian'),
    ('p220','<Yahya_Ale_Eshaq>','<male>','<Qom>',NULL,NULL,'يحيي ال اسحاق@fas'),
    ('p221','<Heidar_Arfaa>','<male>',NULL,NULL,NULL,'Arfaa'),
    ('p222','<Mohammad_Sa''ed>','<male>','<Maragheh>','<Tehran>',NULL,'محمد ساعد مراغه ای@fas'),
    ('p223','<Mostafa_Mir-Salim>','<male>',NULL,NULL,NULL,'Mostafa Mir-Salim'),
    ('p224','<Nasser_Moghadam>','<male>','<Tehran>','<Tehran>',NULL,'ناصر مقدم@fas'),
    ('p225','<nl/Ali_Razmara>',NULL,NULL,NULL,NULL,'Razmara@nl'),
    ('p226','<Mostafa_Moeen>','<male>','<Najafabad>',NULL,'<http://www.Moeen.ir/>','مصطفی معین@fas'),
    ('p227','<Abdol-Hossein_Mirza_Farmanfarma>',NULL,'<Tabriz>','<Tehran>',NULL,'عبدالحسين خان فرمانفرما@fas'),
    ('p228','<Jafar_Towfighi>','<male>',NULL,NULL,NULL,'جعفر توفيقي داريان@fas'),
    ('p229','<Hassan_Ali_Mansur>','<male>','<Tehran>','<Tehran>',NULL,'حسن علی منصور@fas'),
    ('p230','<Mohammad_Javad_Tondguyan>','<male>',NULL,NULL,NULL,'Mohammad'),
    ('p231','<Hossein_Namazi>','<male>',NULL,NULL,NULL,'Hossein Namazi@eng'),
    ('p232','<Heydar_Moslehi>','<male>','<Shahreza>',NULL,NULL,'حيدر مصلحي@fas'),
    ('p233','<Dariush_Homayoon>','<male>','<Tehran>','<Geneva>',NULL,'داريوش همايون@fas'),
    ('p234','<Mohammad_Ali_Foroughi>','<male>','<Tehran>','<Tehran>',NULL,'محمدعلی فروغی@fas'),
    ('p235','<Mahmud_Mahmud>','<male>',NULL,NULL,NULL,'Mahmud Mahmud@eng'),
    ('p236','<Hassan_Pirnia>','<male>','<Tabriz>','<Tehran>',NULL,'حسن پيرنيا@fas'),
    ('p237','<de/Mohammed_Hossein_Saif_Qazi>',NULL,NULL,NULL,NULL,'Seyfi Qazi@kur'),
    ('p238','<Abolhassan_Banisadr>','<male>','<Hamedan>',NULL,NULL,'بنی‌صدر@fas'),
    ('p239','<Karim_Khodapanahi>','<male>',NULL,NULL,NULL,'Karim Khodapanahi'),
    ('p240','<Ali_Shayegan>','<male>',NULL,NULL,NULL,'دكتر شايگان@fas'),
    ('p241','<Amanullah_Jahanbani>','<male>',NULL,NULL,NULL,'امان الله جهانباني@fas'),
    ('p242','<Alireza_Sheikhattar>','<male>',NULL,NULL,NULL,'Ali-Reza@deu'),
    ('p243','<Ali_Akbar_Salehi>','<male>','<Karbala>',NULL,NULL,'علی‌اکبر صالحی@fas'),
    ('p244','<Abdolreza_Rahmani_Fazli>','<male>','<Shirvan,_Iran>',NULL,NULL,'رحمانی فضلی@fas'),
    ('p245','<Teymur_Bakhtiar>','<male>','<Shahr-e_Kord>',NULL,NULL,'سپهبد تيمور بختيار@fas'),
    ('p246','<Hamid_Behbahani>','<male>','<Behbahan>',NULL,NULL,'حمید بهبهانی@fas'),
    ('p247','<Mahmoud_Alavi>','<male>','<Lamerd>',NULL,NULL,'محمود علوي@fas'),
    ('p248','<Morteza_Bakhtiari>','<male>',NULL,NULL,NULL,'Morteza Bakhtiari@eng');
