CREATE TABLE IF NOT EXISTS Prime_Ministers_of_Iran (
    `P_ID` VARCHAR(4) CHARACTER SET utf8,
    `Name` VARCHAR(39) CHARACTER SET utf8,
    `Label` VARCHAR(34) CHARACTER SET utf8,
    PRIMARY KEY (P_ID),
    foreign key (P_ID) REFERENCES Politicians_table(P_ID)
);
INSERT INTO Prime_Ministers_of_Iran VALUES
    ('p1','<Jafar_Sharif-Emami>','شریف امامی@fas'),
    ('p6','<Mirza_Ali_Asghar_Khan_Amin_al-Sultan>','ميرزا علي اصغر امين السلطان@fas'),
    ('p7','<de/Abolqasem_Naser_al_Molk>','Abolqasem Naser al Molk@eng'),
    ('p8','<Ahmad_Qavam>','احمد قوام السلطنه@fas'),
    ('p11','<Hajj_Mirza_Aghasi>','حاجي ميرزا آقاسي@fas'),
    ('p15','<Mohammad-Ali_Rajai>','رجایی@fas'),
    ('p18','<Mohammad-Reza_Mahdavi_Kani>','محمد رضا مهدوي كني@fas'),
    ('p21','<Mohammad-Reza_Hekmat>','Sardar Fakher Hekmat@eng'),
    ('p28','<Mehdi_Bazargan>','مهدی بازرگان@fas'),
    ('p35','<Shapour_Bakhtiar>','دکتر شاپور بختیار@fas'),
    ('p36','<Mohammad_Vali_Khan_Tonekaboni>','سپهدار اعظم تنکابنی@fas'),
    ('p40','<Ali_Amini>','علی امینی@fas'),
    ('p41','<Mohsen_Sadr>','صدرالاشراف@fas'),
    ('p43','<Gholam_Reza_Azhari>','ازهاري@fas'),
    ('p45','<Manouchehr_Eghbal>','منوچهر اقبال@fas'),
    ('p51','<Mohammad-Javad_Bahonar>','آيت الله دكتر باهنر@fas'),
    ('p63','<Mohammad-Reza_Bahonar>','محمد رضا باهنر@fas'),
    ('p64','<Mirza_Hosein_Khan_Moshir_od-Dowleh>','ميرزا حسين خان مشيرالدوله@fas'),
    ('p89','<Morteza_Gholi_Khan_Hedayat>','مرتضی‌قلی‌خان هدایت@fas'),
    ('p92','<fr/Mehdi_Gholi_Hedayat>','Mehdi Hedayat@fr'),
    ('p102','<Abdol_Majid_Mirza>','عین‌الدوله@fas'),
    ('p106','<Mirza_Nasrullah_Khan>','نصرالله مشیرالدوله@fas'),
    ('p112','<Mahmoud_Jam>','محمود جم@fas'),
    ('p115','<Morteza-Qoli_Bayat>','سهام السلطان بيات@fas'),
    ('p119','<Ali_Soheili>','علی سهیلی@fas'),
    ('p120','<Mehdi_Qoli_Hedayat>','ميرزا مهدي قلي خان مخبرالسلطنه@fas'),
    ('p121','<Vosough_od-Dowleh>','حسن وثوق@fas'),
    ('p122','<Fathollah_Khan_Akbar>','فتح الله خان سپهدار رشتی@fas'),
    ('p125','<Ali_Mansur>','منصور الملک@fas'),
    ('p126','<Mostowfi_ol-Mamalek>','حسن مستوفی‌الممالک@fas'),
    ('p127','<Mirza_Ali_Asghar_Khan_Amin_al-Soltan>','al-Soltan'),
    ('p134','<Saad_ad-Daula>','نجفقلی بختیاری@fas'),
    ('p139','<Fazlollah_Zahedi>','فضل الله خان بصير ديوان@fas'),
    ('p141','<Amir-Abbas_Hoveyda>','عباس هويدا@fas'),
    ('p142','<Jamshid_Amouzegar>','جمشید اموزگار@fas'),
    ('p150','<Asadollah_Alam>','امير اسدالله علم@fas'),
    ('p155','<Abdolhossein_Hazhir>','هژير@fas'),
    ('p163','<fr/Reza_Sardar_Fakher_Hekmat>','Hekmat@fr'),
    ('p169','<Amir_Kabir>','میرزا تقی خان امیر کبیر@fas'),
    ('p171','<Hossein_Ala''>','حسين علاء@fas'),
    ('p174','<Haj_Ali_Razmara>','حاجیعلی رزم آرا@fas'),
    ('p185','<nl/Jafaar_Sharif-Emami>','Jafaar Sharif-Emami@eng'),
    ('p187','<Zia''eddin_Tabatabaee>','سیدضیاالدین طباطبائی@fas'),
    ('p190','<Ebrahim_Hakimi>','ابراهیم حکیم الممالک@fas'),
    ('p192','<Mohammad_Mosaddegh>','محمد مصدق السلطنه@fas'),
    ('p203','<Rezā_Shāh>','رضا خان پهلوي@fas'),
    ('p204','<Mir-Hossein_Mousavi>','میرحسین موسوی خامنه ای@fas'),
    ('p210','<Ahmad_Matin-Daftari>','متین الدوله@fas'),
    ('p212','<Ghaem_Magham_Farahani>','قائم مقام فراهانی@fas'),
    ('p213','<Mahmoud_Djam>','Mahmoud Djam@eng'),
    ('p214','<de/Najaf_Qoli_Khan_Samsam_al-Saltaneh>','Saltaneh@deu'),
    ('p218','<de/Mohammad_Ali_Khan_Ala_al-Saltaneh>','میرزا محمدعلی خان علاءالسلطنه@fas'),
    ('p222','<Mohammad_Sa''ed>','محمد ساعد مراغه ای@fas'),
    ('p225','<nl/Ali_Razmara>','Razmara@nl'),
    ('p227','<Abdol-Hossein_Mirza_Farmanfarma>','عبدالحسين خان فرمانفرما@fas'),
    ('p229','<Hassan_Ali_Mansur>','حسن علی منصور@fas'),
    ('p234','<Mohammad_Ali_Foroughi>','محمدعلی فروغی@fas'),
    ('p236','<Hassan_Pirnia>','حسن پيرنيا@fas');
