CREATE TABLE IF NOT EXISTS University_Table_nahai (
    `U_ID` VARCHAR(3) CHARACTER SET utf8,
    `Name` VARCHAR(42) CHARACTER SET utf8,
    `Label` VARCHAR(27) CHARACTER SET utf8,
        primary key(U_ID)
);
INSERT INTO University_Table_nahai VALUES
    ('u1','<University_of_Tehran>','دانشگاه تهران@fas'),
    ('u2','<K.N.Toosi_University_of_Technology>','دانشگاه خواجه نصیر@fas'),
    ('u3','<San_Jose_State_University>','دانشگاه ايالتي سان خوزه@fas'),
    ('u4','<University_of_Pune>','University of Pooma@eng'),
    ('u5','<California_Polytechnic_State_University>',NULL),
    ('u7','<Pantheon-Sorbonne_University>',NULL),
    ('u8','<University_of_Nottingham>',NULL),
    ('u10','<École_Centrale_Paris>',NULL),
    ('u12','<National_War_College>',NULL),
    ('u14','<Shiraz_University>',NULL),
    ('u17','<California_State_University,_Los_Angeles>',NULL),
    ('u21','<Glasgow_Caledonian_University>',NULL),
    ('u23','<University_of_Glasgow>',NULL),
    ('u24','<Qom_Hawza>',NULL),
    ('u26','<University_of_Houston>',NULL),
    ('u27','<Shahid_Chamran_University_of_Ahvaz>',NULL),
    ('u30','<Texas_A&M_University>',NULL),
    ('u31','<University_of_California,_Berkeley>',NULL),
    ('u32','<University_of_Kentucky>',NULL),
    ('u33','<University_of_Cambridge>',NULL),
    ('u34','<San_Francisco_State_University>',NULL),
    ('u35','<University_of_Denver>',NULL),
    ('u36','<Sharif_University_of_Technology>',NULL),
    ('u37','<Shahid_Bahonar_University_of_Kerman>',NULL),
    ('u38','<Shiraz_University_of_Medical_Sciences>',NULL),
    ('u41','<Islamic_Azad_University>',NULL),
    ('u42','<University_of_Oxford>',NULL),
    ('u44','<University_of_Paris>',NULL),
    ('u45','<Utah_State_University>',NULL),
    ('u46','<Tarbiat_Modares_University>',NULL),
    ('u47','<University_of_Isfahan>',NULL),
    ('u51','<Massachusetts_Institute_of_Technology>',NULL),
    ('u55','<Johns_Hopkins_University>',NULL),
    ('u60','<Cornell_University>',NULL),
    ('u64','<Ferdowsi_University_of_Mashhad>',NULL),
    ('u69','<Imam_Hossein_University>',NULL),
    ('u70','<Baylor_University>',NULL),
    ('u72','<Supélec>',NULL),
    ('u73','<American_University_of_Beirut>',NULL),
    ('u76','<University_of_Saskatchewan>',NULL),
    ('u77','<Allameh_Tabatabaei_University>',NULL),
    ('u79','<University_of_Neuchâtel>',NULL),
    ('u80','<Sciences_Po>',NULL),
    ('u84','<Stanford_University>',NULL),
    ('u86','<Shahid_Beheshti_University>',NULL),
    ('u87','<Iowa_State_University>',NULL),
    ('u90','<University_of_Lausanne>',NULL),
    ('u95','<Tehran_School_of_Political_Science>',NULL);
